server:
  pub_endpoint: "tcp://*:5555"
  router_endpoint: "tcp://*:5556"
  render_interval: 300

storage:
  enabled: false
  base_path: "./data"
  depth: 20 # depth levels to store (bids + asks)
  flush_interval: 1000 # ms between BufWriter flushes
  rotation: "daily" # "daily" | "none"
  zstd_level: 0 # 0 = disabled, 1–22 = zstd compression level (3 is a good default)

binance:
  enabled: true
  symbols:
    - "btcusdt"
    - "ethusdt"

okx:
  enabled: true
  symbols:
    - "BTC-USDT"
    - "ETH-USDT-SWAP"

hyperliquid:
  enabled: true
  coins: # uppercase coin names
    - "BTC"
    - "ETH"

kalshi:
  market:
    - enable: true
      series: "KXBTC15M"
      interval_secs: 900
    - enable: true
      series: "KXETH15M"
      interval_secs: 900

polymarket:
  markets:
    - enabled: true
      slug: "btc-updown-15m"
      interval_secs: 900
    - enabled: true
      slug: "eth-updown-15m"
      interval_secs: 900

    - enabled: true
      slug: "btc-updown-5m"
      interval_secs: 300

    - enabled: true
      slug: "eth-updown-5m"
      interval_secs: 300

    # example of static market
    - enabled: false 
      slug: "will-btc-reach-100k-in-2025"
      interval_secs: 0